title: Statistical Learning with Python
author: Micha Burkhardt, Constanze Buschmann
logo: logo.png
copyright: "2025"

# Reference: https://jupyterbook.org/en/stable/customize/config.html

# Do not execute notebooks
execute:
  execute_notebooks: "auto"
  exclude_patterns: ["*/Exercises.ipynb"]


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - book/misc/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/mibur1/psy112
  branch: main

# Add GitHub buttons to your book
html:
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  baseurl: https://mibur1.github.io/psy112
  
sphinx:
  html_context:
    default_mode: dark
  recursive_update: true
  extra_css:
    - _static/custom.css
  extra_javascript:
    - _static/custom.js
  config:
    html_js_files:
      - "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"
    
# Google colab launch button
launch_buttons:
  colab_url: "https://colab.research.google.com"
  